import java.util.List;


public class MadLibs {
    public static final List<MadLib> ALL =
    List.of(
        // From VACATION FUN MAD LIBS® • Copyright © 1988 by Price Stern Sloan, a division of Penguin Putnam Books for Young Readers, New York.
        new MadLib(
            "Vacation Fun",
            List.of(
                new FixedText("A vacation is when you take a trip to some"),
                new Substitution("adjective"),
                new FixedText("place with your"),
                new Substitution("adjective"),
                new FixedText("family. Usually you go to some place that is near a/an"),
                new Substitution("noun"), 
                new FixedText("or up on a/an"), 
                new Substitution("noun"), 
                new FixedText(". A good vacation place is one where you can ride"), 
                new Substitution("plural noun"), 
                new FixedText("or play"), 
                new Substitution("game"), 
                new FixedText("or go hunting for"), 
                new Substitution("plural noun"),
                new FixedText(". I like to spend my time"), 
                new Substitution("-ing verb"), 
                new FixedText("or"), 
                new Substitution("-ing verb"), 
                new FixedText("When parents go on a vacation, they spend their time eating three"), 
                new Substitution("plural noun"), 
                new FixedText("a day, and fathers play golf, and mothers sit around"),
                new Substitution("-ing verb"), 
                new FixedText(". Last summer, my little brother fell in a/an"), 
                new Substitution("noun"), 
                new FixedText("and got poison"), 
                new Substitution("plant"),
                new FixedText("all over his"),
                new Substitution("body part"),
                new FixedText(". My family is going to (the)"), 
                new Substitution("place"), 
                new FixedText(". and I will practice"),
                new Substitution("-ing verb"), 
                new FixedText(". Parents need vacations more than kids because parents are always very"),
                new Substitution("adjective"),
                new FixedText("and because they haveto work"),
                new Substitution("number"),
                new FixedText("hours every day all year making enough"),
                new Substitution("plural noun"),
                new FixedText("to pay for the vacation.")
            )
        ),

        // From MAD, MAD, MAD LIBS® • Copyright © 1998 by Price Stern Sloan, a division of Penguin Putnam Books for Young Readers, New York.
        new MadLib(
            "Love Letter",
            List.of(
                new FixedText("My"),
                new Substitution("adjective"),
                new FixedText("darling, I love you more than"),
                new Substitution("noun"), 
                new FixedText("itself. Each minute away from you is a/an"),
                new Substitution("noun"),
                new FixedText("each hour a/an"),
                new Substitution("adjective"),
                new FixedText("eternity. Without you, life if dull, doring, and"),
                new Substitution("adjective"),
                new FixedText("I feel like a baby without my"),
                new Substitution("noun"),
                new FixedText(", a toddle without my teddy"),
                new Substitution("noun"),
                new FixedText(", a dog without its"),
                new Substitution("noun"),
                new FixedText(". I can't get you out of my"),
                new Substitution("body part"),
                new FixedText(". I can't stop thinking about the color of your"),
                new Substitution("noun"),
                new FixedText(", the way you wear your"),
                new Substitution("noun"), 
                new FixedText(", the way you toss your"),
                new Substitution("noun"),
                new FixedText(", your"),
                new Substitution("adjective"),
                new FixedText("laugh, they way you"),
                new Substitution("verb"),
                new FixedText("a joke. This morning, when the mail"),
                new Substitution("noun"),
                new FixedText("brought your special delivery"),
                new Substitution("plural noun"),
                new FixedText(", my"),
                new Substitution("body part"),
                new FixedText("skipped a beat, my"), 
                new Substitution("body part"), 
                new FixedText("was in my throat, and my"),
                new Substitution("noun"),
                new FixedText("trembled so much, I could hardly"),
                new Substitution("verb"),
                new FixedText("your"),
                new Substitution("noun"),
                new FixedText(". What you said set my"),
                new Substitution("noun"),
                new FixedText("on fire. Do write again. Until then, I love you from the bottom of my"),
                new Substitution("body part"),
                new FixedText(". I will"),
                new Substitution("verb"), 
                new FixedText("you always, "), 
                new Substitution("your name")
            )
        ),

        // From MAD LIBS® FROM OUTER SPACE • Copyright © 1989 by Price Stern Sloan, a division of Penguin Putnam Books for Young Readers, New York.
        new MadLib(
            "Our Solar System",
            List.of(
                new FixedText("When we look up into the sky on a/an"),
                new Substitution("adjective"),
                new FixedText("summer night, we see millions of tiny spots of light. Each one represents a/an"),
                new Substitution("noun"), 
                new FixedText("which is the center of a/an"),
                new Substitution("adjective"),
                new FixedText("solar system with dozens of"),
                new Substitution("plural noun"),
                new FixedText("revolving"),
                new Substitution("adjective"),
                new FixedText("around a distant sun. Sometimes these suns expand and begin"), 
                new Substitution("-ing verb"),
                new FixedText("their neighbors. Soon they will become so big, they will turn into"),
                new Substitution("silly word pl."),
                new FixedText(". Eventually they subside and become"),
                new Substitution("adjective"),
                new FixedText("giants or perhaps black"),
                new Substitution("plural noun"),
                new FixedText(". Our own planet, which we call"),
                new Substitution("first name"), 
                new FixedText(", circles around our"),
                new Substitution("adjective"),
                new FixedText("sun"), 
                new Substitution("number"), 
                new FixedText("times every year. There are eight other planets in our solar system. They are named"),
                new Substitution("first name"),
                new FixedText(", "),
                new Substitution("first name"),
                new FixedText(", "),
                new Substitution("first name"),
                new FixedText(", "),
                new Substitution("first name"),
                new FixedText(", "),
                new Substitution("first name"),
                new FixedText(", "),
                new Substitution("first name"),
                new FixedText(", Jupiter, and Mars. Scientists who study these planets are called"),
                new Substitution("plural noun"),
                new FixedText(".")
            )
        )
    );
}
